Feature/1 start
mister-Mandarin/PurpleSchool-ReactCource-Films pull request #1
Opened 2024-01-22 08:52 UTC by mister-Mandarin

Выполнил 3 дз, отправляют на ревью. 

Столкнулся с проблемой в компоненте CardFilm.jsx при изменении состоянии при клике добавить в избранное. Мне кажется получился колхоз и можно как то лаконичней сделать, например вынести в отдельный компонент, а может это будет уже излишне.
Еще не получилось через css изменить цвет svg иконки bookmark. Вообще ни в какую, даже если напрямую стили прописывать. Пришлось делать отдельную иконку с другим цветом. 
Еще для каждой карточки фильма делать отдельное состояние это нормально? Или есть более оптимальный способ. Это если список из 150 фильмов, то будет создано 150 одинаковых функций обработки состояния.

Остальное мне кажется нормальным и особых проблем не было)

2024-01-22 18:48 UTC, Levitinn commented
Столкнулся с проблемой в компоненте CardFilm.jsx при изменении состоянии при клике добавить в избранное. Мне кажется получился колхоз и можно как то лаконичней сделать, например вынести в отдельный компонент, а может это будет уже излишне.
вообще пока убери логику добавления в избранное, сделай так, чтобы карточка лишь отображала, что фильм в избранном, если он там. а там ли он храни пока в объекте фильма
` {
    "id": 1,
    "title": "Black Widow",
    "img": "../src/CardsField/data/img/Black-Widow.jpg",
    "rate": 324,
    "isFavorite": true,
  },`



Еще не получилось через css изменить цвет svg иконки bookmark. Вообще ни в какую, даже если напрямую стили прописывать. Пришлось делать отдельную иконку с другим цветом.
Еще для каждой карточки фильма делать отдельное состояние это нормально? Или есть более оптимальный способ. Это если список из 150 фильмов, то будет создано 150 одинаковых функций обработки состояния.

2024-01-22 18:49 UTC, Levitinn requested changes

2024-01-22 18:49 UTC, Levitinn commented on src/App.jsx
> +			<HeaderDescription className={'description-title'} text={'Введите название фильма, сериала или мультфильма для поиска и добавления в избранное.'} />
это просто текст. который можно рендерить где угодно, не только в хедере. не нужно привязывать имя компонента к хедеру

2024-01-22 18:49 UTC, Levitinn commented on src/App.jsx
> +			<HeadTitle Tag={'h3'} className={'small'} text={'Avengers: Endgame'} />
тоже самое, ты передаешь тег и сам текст, значит, можно использовать этот компонент где угодно. сделай название более универсальным

2024-01-22 18:49 UTC, Levitinn commented on src/App.jsx
в этом компоненте у тебя рендерятся все остальные компоненты одной большой колбасой. сделай так чтобы здесь внутри тебя были header и body компоненты, а внутри них соответствующие компоненты

2024-01-22 18:49 UTC, Levitinn commented on src/App.jsx
> +			<CardsField>
не нужно сюда чилдрен передавать. сделай чтобы компонент принимал массив фильмов и внутри сбея имел логику рендера карточек фильмов

2024-01-22 18:49 UTC, Levitinn commented on src/CardFilm/CardFilm.jsx
> +				<span>{rate}</span>
рейтинг это отдельный компонент

2024-01-22 18:49 UTC, Levitinn commented on src/CardFilm/CardFilm.jsx
> +			<span>{title}</span>
если у какого то фильма нет названия - твой код упадет

2024-01-22 18:49 UTC, Levitinn commented on src/CardFilm/CardFilm.jsx
> +			<div className={cl} onClick={changeFavorite}>
ты создал отдельную функцию changeFavorite , внутри которой лишь одна строка, уж лучше выполняй ее прямо внутри
`<div className={cl} onClick={() => setAddFavorite(!addFavorite)}>`


так код будет чище

2024-01-22 18:49 UTC, Levitinn commented on src/CardsField/CardsField.jsx
сюда логику рендера карточек фильмов

2024-01-22 18:49 UTC, Levitinn commented on src/Layout/Layout.jsx
это скорее header, чем layout

2024-01-22 19:28 UTC, mister-Mandarin commented on src/CardFilm/CardFilm.jsx
> +				<span>{rate}</span>
Почему это должен быть отдельный компонент? Чем он это заслужил?

2024-01-22 19:35 UTC, mister-Mandarin commented on src/CardFilm/CardFilm.jsx
> +			<span>{title}</span>
Разве может быть фильм без названия?) Я попробовал убирать разные данные из json и ничего не ломается. Консоль тоже молчит.

2024-01-22 19:37 UTC, mister-Mandarin commented on src/Layout/Layout.jsx
Антон в задании его Layout назвал, думал так и должно быть.

2024-01-23 11:12 UTC, mister-Mandarin commented
Добавил в json с данными поле "isFavorite": true. 
Изменил название компонентов заголовка и описания на более универсальные.

"в этом компоненте у тебя рендерятся все остальные компоненты одной большой колбасой. сделай так чтобы здесь внутри тебя были header и body компоненты, а внутри них соответствующие компоненты" - с этим не совсем понял что надо сделать. В app.jsx оставил компонент хедера, а остальное поместил в див контейнер с классом body-container.

Перенес логику рендера карточек из app в CardsField/

Переименовал компонент layout в header.

2024-01-23 18:27 UTC, Levitinn requested changes

2024-01-23 18:27 UTC, Levitinn commented on src/CardFilm/CardFilm.jsx
> +				<span>{rate}</span>
потому что это часть логики и верстки, которая используется в каждой карточке фильма. все что переиспользуемое и имеет какую то внутреннюю логику - отдельный компонент

2024-01-23 18:27 UTC, Levitinn commented on src/CardFilm/CardFilm.jsx
> +			<span>{title}</span>
молчит, верно. но так быть не должно. это уязвимость

2024-01-23 18:27 UTC, Levitinn commented on src/CardsField/CardsField.jsx
> +		<div className='cards-field'>
нет проверки, что Data пустая

2024-01-25 06:09 UTC, mister-Mandarin commented
Правки-2 ДЗ

Сделал отдельный компонент body в котором рендерится основная страница. Я еще понял, что он нужен будет, чтобы в нем же рендерить и другие страницы когда будем роуты изучать. Не по условию же отображать страницы.

Добавил проверку наличия данных в Data и текст в случае их отсутствия.

Рейтинг карточки фильма вынес в отдельный компонент.

Добавил проверку на название фильма. Наверно тогда логичнее будет делать проверку наличия всех данных перед рендером каждой карточки, и если чего то не хватает то не судьба)

2024-01-25 18:12 UTC, Levitinn requested changes

2024-01-25 18:12 UTC, Levitinn commented on src/App.jsx
по факту, сейчас в компоненте App не уменьшилось, а увеличилось число компонентов.
моя мысль была в том, чтобы в Арр у тебя был хедер и боди. и больше ничего. Боди внутри себя уже сам будет рендерить нужные компоненты. А ты передал их чилдренами.
По факту у тебя сейчас  компонент боди только лишь добавляет чилдренам див с классом body-container. для этих целей создавать целый компонент нет смысла. 
Сделай чтобы боди ничего внутрь себя не принимал, а внутри сам рендерил нужные компоненты

2024-01-25 18:12 UTC, Levitinn commented on src/Button/Button.jsx
> +		<>
<> здесь лишние

2024-01-25 18:12 UTC, Levitinn commented on src/CardsField/CardsField.jsx
> +			{Data && Data.length > 0 ?
своим условием `{Data && Data.length > 0 ?.......`
ты внес логику внутрь верстки компонента, то есть на этапе рендера реакт будет вычислять какой кусок кода ему рендерить. Эту часть можно оптимизировать, если поставить условие перед return компонента, например так:

`export default function CardsField() {

if (!data.length) return (
   <div className='cards-field'>
             <TextParagraph text={'Нет данных для отображения'}/>
     </div>
)

return (
<div className='cards-field'>
       //здесь уже точно известно, что дата есть, иначе выполнился бы первый if и сюда код не дошел
      Data.map(el => (
					<CardFilm
						key={el.id}
						title={el.title}
						rate={el.rate}
						img={el.img}
						isFavorite={el.isFavorite}
					>
					</CardFilm>
				))
</div>
)
}`

2024-01-29 06:12 UTC, mister-Mandarin commented
Правки-3 ДЗ
Оставил только 2 компонента в app
Исправил Button.jsx.
Добавил проверку всех данных карточки, и если чего то не хватает, то она не отображается. 
Добавил условие проверки наличия Data перед рендером карточек фильмов. Правда если массив будет вида [{}] то просто ничего не отображается. Не знаю считается ли это ошибкой или нет.

2024-01-29 17:49 UTC, Levitinn approved these changes
принимаю, но оставляю комментарий нужно обязательно исправить

2024-01-29 17:49 UTC, Levitinn commented on src/CardsField/CardsField.jsx
> +export default function CardsField() {
дату лучше импортировать в компоненте выше, и передавать пропсом внутрь этого компонента

2024-01-31 14:25 UTC, merged