Feature/2 start
mister-Mandarin/PurpleSchool-ReactCource-Films pull request #2
Opened 2024-02-07 12:30 UTC by mister-Mandarin

Завершил ДЗ в уроке 6.7
Добавил библиотеку classnames
Заменил стили на module
Перенес вызов Data в body

2024-02-14 09:15 UTC, mister-Mandarin commented
Слишком много я тут нахуевертил и по хорошему кодревью надо было бы еще ставить после создания своего хука так как ошибки в логике там - приведут к ошибкам здесь. 

Приложение не работает и не понимаю куда капать. Мне кажется я слишком много разных зависимостей сделал которые зависят друг от друга, value из локастореджа, state и auth. 

Моя локига:
 при нажатии кнопки "вход" с логином, он записывался в стейт, отуда в локасторедж и дальше в контекст auth  -  состояние в header меняется, работает;
 еще раз если ввести другой логин и войти - то старый не меняется, странно, ведь механизм тот же;
 если обновить страницу, то данные в auth когда то загружаются, когда то сбрасывается. Еще при первом вызове auth пустой, а потом вызывается второй раз и заполняется данными. Непонятно почему он вызывается в первый раз.

2024-02-15 20:55 UTC, Levitinn requested changes

2024-02-15 20:55 UTC, Levitinn commented on src/Header/Header.jsx
> +					{!auth.isLogin &&
предлагаю вынести авторизации в отдельный компонент, так как у нее своя логика значительная, которую не нужно сувать туда, где она не нужна. хедер никаким образом с авторизацией не связан, потому никакой ее логики внутри хедера быть не должно

2024-02-15 20:55 UTC, Levitinn commented on src/FormLogin/FormLogin.jsx
> +		dispatch({type: 'CHANGE_LOCALSTORAGE'});
кажется нет смысла двух диспатчей, так как при логине тебе всегда нужно обновлять локалстор, и нет смысла вызывать вручную CHANGE_LOCALSTORAGE после ЛОГИН, каждый раз

2024-02-15 20:55 UTC, Levitinn commented on src/FormLogin/FormLogin.jsx
> +	const {updateAuth} = useContext(AuthContext);
мне кажется ты можешь избавиться от контекста вообще, так как у тебя есть редакс который полностью может заменить useContext

2024-02-15 20:55 UTC, Levitinn commented on src/FormLogin/FormLogin.jsx
> +	const {updateAuth} = useContext(AuthContext);
разносить стейты по разным сторам не хорошо. по сути это просто засоряет проект

2024-02-15 20:55 UTC, Levitinn commented on src/CardsField/CardsField.jsx
>  	if (!Data || !Data.length) {
if (!Data) достаточно. если даты нет, то и длинны у нее нет. просто сделай чтобы дата была null если в ней ниче нет

2024-02-15 20:55 UTC, Levitinn commented on src/CardsField/CardsField.jsx
> +export default function CardsField({Data}) {
пропсы с маленькой буквы должны быть

2024-02-15 20:55 UTC, Levitinn commented on src/CardsField/CardsField.jsx
>  				if (el.id && el.title && el.rate && el.img) {
думаю тут нужно просто передавать все данные что есть внутрь CardFilm, проверяя например, только ИД. 
а внутри CardFilm уже делать проверки на заголовки, рейтинг и тд. ведь если апи тебе не отдало рейтинг, ты же все равно можешь отобразить этот фильм, просто без рейтинга

2024-02-15 20:55 UTC, Levitinn commented on src/CardFilm/CardFilm.jsx
>  			{title && <span>{title}</span>}
`<span>{title || ''}</span>`
чтобы тег всегда был, а то если его не будет, высота карточки или ее контента будет меняться, а нам это не нужно

2024-02-15 20:55 UTC, Levitinn commented on src/CardFilm/CardFilm.jsx
> +			<div className={cn(styles.favorite, {
всю логику избранного, вынеси в отдельный компонент, чтобы здесь ее не было

2024-02-16 09:55 UTC, mister-Mandarin commented on src/FormLogin/FormLogin.jsx
> +	const {updateAuth} = useContext(AuthContext);
Пока редакса нет, задача использовать контекст для обновления состояния авторизации

2024-02-16 13:46 UTC, mister-Mandarin commented
Правки ДЗ.

Вынес авторизацию в отдельный компонент в хедере
Изменил проверку данных отрисовки в карточке фильма. Если есть id то карточка будет, а дальше отображение зависит от данных c api.
Логику избранного вынес в отдельный компонент. 

Я пытался удерживать одновременно 3 состояния, это контекст, локалстор и стейт. В итоге прокинул стейт через контекст. Логику работы с локалстором из стейта формы вынес в хук работы с локалстором. И... все как то веселее и понятнее стало сразу. 

Сейчас проблема в том, что когда ввожу данные в поле формы входа они сразу появляются в хедере. Не знаю это ошибка или нет, может еще 15 раз все изменится, поэтому отправляю на ревью.

2024-02-17 10:35 UTC, Levitinn commented on src/FormLogin/FormLogin.jsx
> +		console.log(state);
никаких консоль логов в мр быть не должно

2024-02-17 10:35 UTC, Levitinn commented on src/FormLogin/FormLogin.jsx
> +		dispatch({type: 'CHANGE_LOCALSTORAGE'});
это не решение проблемы. ты заменил один из двух диспатчей на контекст. я предлагал тебе засунуть логику сохранения в ЛС стейта, прямо внутри функции диспатча "логин" так как всегда при логине ты хочешь сохранять в ЛС данные. так и сделай это все в одном екшене. зачем разделять логику, которая всегда используется совместно

2024-02-17 10:47 UTC, Levitinn commented
> Сейчас проблема в том, что когда ввожу данные в поле формы входа они сразу появляются в хедере. Не знаю это ошибка или нет, может еще 15 раз все изменится, поэтому отправляю на ревью.

это однозначно ошибка. пока пользователь не авторизован, его имя не должно отображаться в кнопке профиля.
во первых,  кнопка профиля в хедере не просто ссылка, потому сделай отдельный компонент под профиль, а не хедерЛинк как сейчас. так же и войти\выйти не хедер линк

2024-02-17 10:47 UTC, Levitinn requested changes

2024-02-17 10:47 UTC, Levitinn commented on src/Header/HeaderAuth/HeaderAuth.jsx
> +export default function HeaderAuth() {
назови просто Auth.  Авторизация никаким образом не связана с хедером, по смыслу. только тем что она рендерится в хедере, но название к нему привязывать не стоит. это обособленный компонент

2024-02-17 10:47 UTC, Levitinn commented on src/Header/HeaderAuth/HeaderAuth.jsx
> +			{state.name.length > 0 &&
отступы поехали. обращай внимание, чтобы каждая "вложенная строка" начиналась с отступом в один таб. в будущем, я буду помечать компонент с поехавшими отступами как не принятый

2024-02-17 10:47 UTC, Levitinn commented on src/Header/HeaderAuth/HeaderAuth.jsx
> +			{state.isLogin &&
![image](https://github.com/mister-Mandarin/PurpleSchool-ReactCource-Films/assets/44999446/437eeef8-89e7-47bd-a295-6060cfb345af)
так корректнее.

2024-02-17 10:47 UTC, Levitinn commented on src/Header/HeaderAuth/HeaderAuth.jsx
> +	function logOut() {
назови его handleAuthAction и через условие внутри используй логику для логина и для логаута. и передавай эту функцию и в онКлик 
![image](https://github.com/mister-Mandarin/PurpleSchool-ReactCource-Films/assets/44999446/920d75b2-7c65-4e6e-b1f0-67e01a03ce34)
а то сейчас у тебя на выйти есть онклик с логаутом, а на логин онклик нет, его логика почему то внутри хедерЛинк, где быть вообще не должна

2024-02-20 06:18 UTC, mister-Mandarin commented
Правки ДЗ. 

Разобрался почти со всеми проблемами. Дошел до момента когда "авторизация" работает, но при перезагрузке страницы сбрасывается состояние в хедере из-за юзеэфеекта в /AuthUser.context.jsx 
```
useEffect(() => {
		setValueLocalstor(state);
		console.log('вызов');
	}, [state]);
```
Пару часов жонглирования if/else и изменения отслеживаемых состояний результатов не дало. ChatGPT предложил вариант сохранять результат через useRef и сравнивать его с текущим. Врятли я бы до такого сам додумался.

Не знаю на сколько оптимально и эффективно, но хотя бы работает)

2024-02-20 19:59 UTC, Levitinn commented
> Правки ДЗ.
> 
> Разобрался почти со всеми проблемами. Дошел до момента когда "авторизация" работает, но при перезагрузке страницы сбрасывается состояние в хедере из-за юзеэфеекта в /AuthUser.context.jsx
> 
> ```
> useEffect(() => {
> 		setValueLocalstor(state);
> 		console.log('вызов');
> 	}, [state]);
> ```
> 
> Пару часов жонглирования if/else и изменения отслеживаемых состояний результатов не дало. ChatGPT предложил вариант сохранять результат через useRef и сравнивать его с текущим. Врятли я бы до такого сам додумался.
> 
> Не знаю на сколько оптимально и эффективно, но хотя бы работает)

юзРеф как вариант. А еще можно в контексте сделать что то подобное 
`const {valueLocalstor, setValueLocalstor} = useLocalStorage(localStorage.profile || '');`

2024-02-20 19:59 UTC, Levitinn requested changes

2024-02-20 19:59 UTC, Levitinn commented on src/CardsField/CardsField.jsx
> +	if (!data) {
if (!data) return <TextParagraph text={'Нет данных для отображения'}/>

2024-02-20 19:59 UTC, Levitinn commented on src/Auth/Auth.jsx
> +	const {dispatch, valueLocalstor} = useContext(AuthContext);
valueLocalstor - некорректное название. не говорит о том, что в нем хранится

2024-02-20 19:59 UTC, Levitinn commented on src/Auth/Auth.jsx
> +				<HeaderLink
почему на выйти есть обработчик, а на войти нет?

2024-02-25 12:54 UTC, mister-Mandarin commented
исправил замечания

2024-02-26 12:57 UTC, Levitinn requested changes
чуть чуть доработать

2024-02-26 12:57 UTC, Levitinn commented on src/Auth/Auth.jsx
> +	function logOut() {
оба обработчика моно заменить одним и по условию выполнять нужный диспатч

2024-02-26 12:57 UTC, Levitinn commented on src/Auth/Auth.jsx
> +			{authState.isLogin ?
повторяющееся условие. его можно использовать один раз и рендерить, что нужно

2024-02-26 12:57 UTC, Levitinn commented on src/context/AuthUser.context.jsx
> +	// идея от chatGPT, сам бы я до конца месяца думал как сохранить предыдущее состояние
лишние комментарии нужно убрать

2024-02-26 15:19 UTC, mister-Mandarin commented on src/Auth/Auth.jsx
> +	function logOut() {
Мне раздельные понятнее. Исправлю

2024-02-27 07:46 UTC, mister-Mandarin commented
Исправил. Как же тогда комментарии правильно в тексте оставлять чтобы понять где что и зачем я писал?

2024-02-27 16:02 UTC, Levitinn commented
> Исправил. Как же тогда комментарии правильно в тексте оставлять чтобы понять где что и зачем я писал?

комментарии которые нужны для понимания логики не являются не нужными =)
не закрывай мои комментарии. я сам помечаю резолв если ты исправил то, что нужно. иначе я не вижу, что комментировал

2024-02-27 16:05 UTC, Levitinn commented on src/Auth/Auth.jsx
> +			{authState.isLogin ?
так лучше
![image](https://github.com/mister-Mandarin/PurpleSchool-ReactCource-Films/assets/44999446/49bd33ff-b6ef-4dd5-8c3a-48f5d043a590)

2024-02-27 16:06 UTC, Levitinn approved these changes
оставил один коммент.
доработай со следующим заданием, он не критичен

2024-02-28 06:46 UTC, merged