Начинаю 3 ДЗ
mister-Mandarin/PurpleSchool-ReactCource-Films pull request #4
Opened 2024-03-01 13:21 UTC by mister-Mandarin

2024-03-01 13:22 UTC, mister-Mandarin commented
Внес изменения с предыдущего пулреквеста. Начинаю переезд на TS.

2024-03-08 17:43 UTC, mister-Mandarin commented
ДЗ 10.8 переход на TS. 

Вроде все типизировал что смог. Компилятор вебшторма выдает ошибку, что не может типизировать useReducer и не знает что такое state и dispatch. Вроде и ругается, но все же и так работает) ХЗ что ему надо от меня)))

2024-03-10 18:57 UTC, Levitinn requested changes
В целом все ок, кроме пары моментов. CardFilm прокомментил и нужно типизировать состояния из контекста и стейтов. вот так быть не должно 
![image](https://github.com/mister-Mandarin/PurpleSchool-ReactCource-Films/assets/44999446/4cebfc28-50db-4f11-b818-920422097ae7)

2024-03-10 18:57 UTC, Levitinn commented on src/Body/Body.jsx
Почему Body лежит вне папки компонентс? если не туда, то создай отдельную папку Pages например, и туда положи Боди)

2024-03-10 18:57 UTC, Levitinn commented on src/components/CardFilm/CardFilm.tsx
> +	el: {
лишняя обертка, передавай каждый из параметров пропсами, чтобы избавиться от el. он здесь лишний

2024-03-11 07:26 UTC, mister-Mandarin commented on src/Body/Body.jsx
На тот момент я еще не знал о pages)

2024-03-13 09:53 UTC, mister-Mandarin commented
Исправил ошибки типизации, подчеркнутых ошибок нет.

2024-03-13 18:25 UTC, Levitinn commented on src/Body/Body.jsx
так исправь сейчас)

2024-03-13 18:26 UTC, Levitinn commented on src/components/CardFilm/CardFilm.tsx
> +	el: {
![image](https://github.com/mister-Mandarin/PurpleSchool-ReactCource-Films/assets/44999446/c0902de5-3427-4127-b7dc-f68e6001e9a8)
поправь отступы. лишний таб

2024-03-13 18:27 UTC, Levitinn requested changes
молодец. чуть чуть осталось

2024-03-17 17:41 UTC, mister-Mandarin commented
Сделал вторую часть ДЗ с добавлением навигации.

Выделил компонент с лейаутом и страницами, наконец то я знаю что это такое и зачем нужно. Теперь все смотрится понятнее и понятно зачем все выносилось в разные компоненты в начале проекта. 

Не знаю как быть с компонентом CardsField, может стоит его совместить с main.
Когда нажимаешь выход не всегда обновляется состояние выхода. Иногда нужно  обновлять страницу. Может это исправится когда будет работа с нормальным сервером

2024-03-19 20:15 UTC, Levitinn commented
> Сделал вторую часть ДЗ с добавлением навигации.

после авторизации, уводи пользователя со страницы входа, и сделай так, чтобы он не мог туда попасть, пока авторизован


> Не знаю как быть с компонентом CardsField, может стоит его совместить с main.

Не стоит
> Когда нажимаешь выход не всегда обновляется состояние выхода. Иногда нужно обновлять страницу. Может это исправится когда будет работа с нормальным сервером

нет. проблема в твоем контексте, а именно с условием. смотри, при авторизации первый лог отрабатывает, а второй нет , потому состояние меняется не сразу, а после перезагрузки. попробуй вообще избавиться от preIsLoginRef. он кажется тут лишним

2024-03-19 20:15 UTC, Levitinn requested changes
Оставил коммент в МР, под твоим сообщением

2024-03-20 08:32 UTC, mister-Mandarin commented
Исправил проблемы с авторизацией. Теперь состояние сразу обновляется при входе и выходе без перезагрузки страницы.

2024-03-20 19:57 UTC, Levitinn commented
> Исправил проблемы с авторизацией. Теперь состояние сразу обновляется при входе и выходе без перезагрузки страницы.

зато если перезагрузить страницу, авторизация пропадает

2024-03-20 19:57 UTC, Levitinn requested changes
это починил, но теперь другая проблема) см. коммент под твоим сообщением

2024-03-21 17:30 UTC, mister-Mandarin commented
Вынес свои идеи в отдельную ветку. Так как useLocalStore и Login.state практически дублировали одно и то же значение и состояние решил или в стейт перенести работу с ЛС, или наоборот. Начал с варианта, отказаться от state и всю логику сделать в хуке по работе с ЛС (просто мне не нравится слово dispatch)

В итоге при попытке входа я напрямую передаю имя пользователя через e.target.loginName.value на вход. 

Хук useLocalStorage стал такой крутой, что может его стоит переименовать в useAuthLocalStorage. Если будет еще необходимость работы с ЛС то разобью его на несколько файлов. 

Удалил очень много лишнего кода, стало даже понятнее.

2024-03-21 17:31 UTC, mister-Mandarin commented
создавал ветку exprompt1, в ней было 2 коммита. Я ее смержил с текущей 3-typescript и удалил

2024-03-21 19:54 UTC, Levitinn commented
> Хук useLocalStorage стал такой крутой, что может его стоит переименовать в useAuthLocalStorage. Если будет еще необходимость работы с ЛС то разобью его на несколько файлов.


не стоит. так как хук для работы с авторизацией, а то, что он использует ЛС внутри себя, это лишь механизм.

2024-03-21 19:54 UTC, Levitinn approved these changes

2024-03-22 05:08 UTC, merged