ДЗ 4
mister-Mandarin/PurpleSchool-ReactCource-Films pull request #5
Opened 2024-03-25 10:48 UTC by mister-Mandarin

2024-03-25 10:52 UTC, mister-Mandarin commented
Сделал 2 задания. В целом все вроде норм работает. Единственный момент в котором так и не разобрался, что на странице Movie.tsx  не работает Suspense fallback.

2024-03-25 20:34 UTC, Levitinn requested changes
![image](https://github.com/mister-Mandarin/PurpleSchool-ReactCource-Films/assets/44999446/10221903-ecfc-49d9-9fb7-6b82ff2bb977)
после авторизации падает ошибка

2024-03-26 05:58 UTC, mister-Mandarin commented
Исправил. Ошибка была в том, что я lazy пытался загрузить лейаут на который происходит навигация после логина

2024-03-26 19:43 UTC, Levitinn requested changes
если при пустом ЛС открыть приложение, то в консоль падает ошибка
![image](https://github.com/mister-Mandarin/PurpleSchool-ReactCource-Films/assets/44999446/68e217cd-f57d-44b7-9f96-1ff8fe01aaa4)
 приложение это не крашит, но сам факт ошибки есть. нужно исправить.
так же, после авторизации меня редиректит на страницу фильмов, однако запрос с фильмамине отправляется, в следствии чего, я вижу пустую страницу фильмов с поиском.
suspence делать не обязательно? ты можешь управлять лоадером на этапе отправки запроса

2024-03-27 14:29 UTC, mister-Mandarin commented
Исправил ошибки в консоли при работе. Исправил ошибки работы с ЛС. 
Добавил фильмы на главной странице при загрузке. Может их стоит прокинуть в контекст и при возврате на предыдущую страницу будут отображаться предыдущие найденные фильмы. 

Осталась проблема с suspens. Не отображается информация что страница фильма загружается. Пробовал компонент в children await поставить. Пробовал данные через useAsyncValue вытаскивать в компоненте. Ничего не работает. fallback отображается только при быстрой перезагрузке страницы с фильмом. А нужно чтобы при ожидании данных с сервера.

2024-03-30 12:23 UTC, mister-Mandarin commented
Ключ апи 33aa5718admshd4507b57e1ed40cp100119jsn052509d104c8

2024-03-31 19:24 UTC, Levitinn requested changes

2024-03-31 19:24 UTC, Levitinn commented on src/main.tsx
> +		const response = await fetch(`${DEFAULT_URL}/titles/${params.id}`, options);
кажется, что все дело в том, что у тебя запрос отправляется выше, то есть сначала реакт дожидается, когда запрос закончится успехом, а затем только редиректит тебя на урл страницы, а так как ответ уже пришел, саспенс не отрабатывает. 
И это кстати, хороший повод исправить этот момент, ведь запрос фильма, ты вынес из компонента страницы фильма наружу, а так делать не стоит. Зачем хранить логику загрузки фильма где то, кроме самого компонента фильма? затащи запрос внутрь, чтобы при переходе на страницу запрос отправлялся, а не заранее. тогда все должно стать ок

2024-04-01 07:52 UTC, mister-Mandarin commented
Функцию перенес, но проблема оказалась в другом. Возвращать данные запроса нужно было через defer. Он возвращает "обещание" вместо разрешения, и благодаря этому происходит сработка suspense. В функции установил задержку в 3 секунды чтобы отследить как отрабатывает fallback.

Сделал файл .env для апи. Вот что внутри:
VITE_API_KEY=33aa5718admshd4507b57e1ed40cp100119jsn052509d104c8
VITE_BASE_URL=moviesdatabase.p.rapidapi.com

2024-04-03 19:18 UTC, Levitinn approved these changes
молодец

2024-04-04 06:04 UTC, merged