5-redux
mister-Mandarin/PurpleSchool-ReactCource-Films pull request #6
Opened 2024-04-03 12:31 UTC by mister-Mandarin

2024-04-03 12:33 UTC, mister-Mandarin commented
Сделал перенос проекта на redux. Теперь в редаксе данные авторизации пользователя и и список избранного

2024-04-03 19:24 UTC, Levitinn requested changes
только один момент меня смущает, молодец.

2024-04-03 19:24 UTC, Levitinn commented on src/components/CardFilm/CardFilm.tsx
> +	function handleClick(e: React.MouseEvent<HTMLDivElement, MouseEvent>) {
логику "в избранное" засунь в компонент CardFilmFavorites? не зря же он у тебя есть.

2024-04-04 10:46 UTC, mister-Mandarin commented
Перенес логику добавления в избранное в компонент CardFilmFavorites.
Исправил отображение рейтинга. В данных апишки значений рейтинга нет, поэтому в этом компоненте отображаю год выхода.

2024-04-04 10:47 UTC, mister-Mandarin commented
ENV файл
VITE_API_KEY=33aa5718admshd4507b57e1ed40cp100119jsn052509d104c8
VITE_BASE_URL=moviesdatabase.p.rapidapi.com

2024-04-06 20:28 UTC, Levitinn approved these changes
молодец. поздравляю)

2024-04-07 06:02 UTC, merged